version: "3.9"

services:
  redis:
    image: redis
    restart: always
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    restart: always

    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  celery:
      build:
        context: .
      command: celery -A todoapp worker -l info
      volumes:
        - .:/code
      env_file:
        - .env
      depends_on:
        - redis
  celery-beat:
    build:
      context: .
    command: celery -A todoapp beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis


