# Generated by Django 3.2.14 on 2022-08-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('full_text', models.TextField()),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('finished', 'Finished')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], default='medium', max_length=6)),
                ('importance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['deadline_date', 'created_date'],
            },
        ),
    ]
